# setopt -s expand_aliases
alias gp="git push origin"
alias rm=trash
alias git=hub
alias f="find . -name"
alias ip="python -m IPython"
alias tk="tmux kill-server"
alias cdv="cd ~/dev"
alias cdi="cd ~/Library/Mobile\ Documents/com~apple~CloudDocs"
alias gd="git diff"
alias tmp="tmp_file"
alias grhh="git reset --hard HEAD"
alias ag="ag --nobreak --nonumbers --noheading . | fzf"
alias nvimr="nvim ~/Library/Mobile\ Documents/com~apple~CloudDocs/config/dotfiles/nvim/init.vim"
alias zshr="vim ~/.zshrc"
alias szh="source_zsh"
alias cdo="cd ~/Library/Mobile\ Documents/com~apple~CloudDocs/config/dotfiles"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias e="fe"
alias gs="git status"
alias ga="git add ."
alias gito="git open"
alias ignore="nvim .gitignore"
alias gm="git commit -m"
alias ll="ls -l"
alias cdt="cd ~/tmp"
alias cgo="cd ~/gocode/src/github.com/wangsongiam/"
alias readme="nvim README.md"
alias ip="ipython"
alias vim="nvim"
alias v="vim"
alias ta="tmux a -d"
# Rust tools
alias ls="exa"
alias rg='rg --hidden'
alias mvim=/Applications/MacVim.app/Contents/bin/mvim
